forge "http://forge.puppetlabs.com"

mod "puppetlabs/stdlib",
    :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod "puppetlabs/firewall",
    :git => "git://github.com/puppetlabs/puppetlabs-firewall.git"

mod "puppetlabs/apache",
    :git => "git://github.com/puppetlabs/puppetlabs-apache.git"

mod "puppetlabs/mysql",
    :git => "git://github.com/puppetlabs/puppetlabs-mysql.git"


mod "archive",
    :git => "git://github.com/camptocamp/puppet-archive.git"

mod "php",
    :git => "git://github.com/brucem/puppet-php.git"
